version: 0.2
# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started.html
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - sed -i -e "s/ADMIN_API_KEY/$ADMIN_API_KEY/g" config/local.example.js
      - sed -i -e "s/TOKEN_SECRET/$TOKEN_SECRET/g" config/local.example.js
      - cd client
      - npm install --only=production
      - npm run build
      - mv build/index.html build/app.html
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - bin/**/*
    - config/**/*
    - client/**/*
    - public/**/*
    - routes/**/*
    - src/**/*
    - views/**/*
    - package.json