apiVersion: v1
kind: Service
metadata:
  name: reciter-pm-dev
  namespace: reciter
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/success-codes: 200-302
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
  labels:
    app: reciter-pm-dev
    environment: dev
    tier: frontend
    owner: szd2013
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: reciter-pm-dev
    tier: frontend
  type: NodePort